# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqcBW36v4s7ruIPvD6jpFVQZ0-D8Rg69
"""

def tashxis (belgi):
    if belgi=="istima":
     return "parasetamol iching"
    elif belgi=="bosh og'riq":
     return "Trimol iching"
    elif belgi=="Tish og'riq":
     return "Kuepen iching"
    elif belgi=="quloq og'riq":
     return "shifokorga murojat qiling"
    elif belgi=="qol og'riq":
     return "maz surting "
    elif belgi=="koz og'riq":
     return "levomiseting quying"
    elif belgi=="bo'gim og'riq":
     return "certofen maz"
    elif belgi=="yelka og'riq":
     return "finalgon maz"
    elif belgi=="bel og'riq":
     return "brufen maz"
    else:
     return "shifokorga murojat qiling"
belgi=input("kasallik belgisini kiriting")
natija=tashxis(belgi)
print(natija)

def fasfud (belgi):
    if belgi=="Hoddog":
     return "mini koralevski 15000 som","big koroloveski 17000 som"
    elif belgi=="Nonburger":
     return "mol go'shti nonburger 35000 ","qo' go'shti nonburger 40000"
    elif belgi=="pizza":
     return "donar 60000","belisimo 99000"
    elif belgi=="gamburger":
     return "rich burger 25000","chikken burger 36000"
    elif belgi=="pepsi fanta":
     return "pepsi 1.5l 12000","fanta 1.5l 12000"
belgi=input("nima buyurtma bermoqchisiz")
natija=fasfud(belgi)
print(natija)